(*
  | Ast.Expr.Identifier id -> Ok ()
  | Ast.Expr.Constant c -> Ok ()
  | Ast.Expr.UnaryOp (op, expr) -> Ok ()
  | Ast.Expr.BinaryOp (op, expr, expr2) -> Ok ()
  | Ast.Expr.Prod (expr1, expr2) -> Ok ()
  | Ast.Expr.Fst expr -> Ok ()
  | Ast.Expr.Snd expr -> Ok ()
  | Ast.Expr.Left (t1, t2, expr) -> Ok ()
  | Ast.Expr.Right (t1, t2, expr) -> Ok ()
  | Ast.Expr.Match (e, iddef1, e1, iddef2, e2) -> Ok ()
  | Ast.Expr.Lambda (iddef, e) -> Ok ()
  | Ast.Expr.Application (e1, e2) -> Ok ()
  | Ast.Expr.IfThenElse (b, e1, e2) -> Ok ()
  | Ast.Expr.LetBinding (iddef, e, e2) -> Ok ()
  | Ast.Expr.LetRec (iddef, e, e2) -> Ok ()
  | Ast.Expr.Box (ctx, e) -> Ok ()
  | Ast.Expr.LetBox (metaid, e, e2) -> Ok ()
  | Ast.Expr.Closure (metaid, exprs) -> Ok ()   
*)
